# Questões Práticas

## Quais questões irei fazer?

In [1]:
def questoes(matricula):
    q = []
    for c in matricula[-6:]:
        n = int(c) + 1
        while n in q:
            n += 1
        q.append(n)
    q.sort()
    return q


print("Minhas questões:", questoes("201812663"))

Minhas questões: [2, 3, 4, 7, 8, 9]

## Importações

In [2]:
import io
import sqlite3
import pandas as pd

conn = sqlite3.connect('tp1.db')
cursor = conn.cursor()

#f = io.open('despesas_publicas_tp1.sql', 'r', encoding='ISO-8859-1')
#sql = f.read()
#cursor.executescript(sql)

## Questão 2
Liste o valor total de despesas públicas por função (nome) e subfunção (nome), apenas nos casos em que esse valor total excedeu 200 mil reais.

In [3]:
query = "SELECT NOME_FUNCAO, NOME_SUBFUNCAO, SUM(VALOR_DESPESA) AS VALOR_TOTAL\
         FROM DESPESA_PUBLICA NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN FUNCAO NATURAL JOIN SUBFUNCAO\
         GROUP BY NOME_FUNCAO, NOME_SUBFUNCAO HAVING VALOR_TOTAL > 200000;"

df = pd.read_sql_query(query, conn);
df

          NOME_FUNCAO           NOME_SUBFUNCAO  VALOR_TOTAL
0  Assistência social  Assistência comunitária    227883.77
1            Educação          Educação básica    334262.06

## Questão 3
Liste todos os nomes dos órgãos e o valor das despesas totais no ano de 2018 para os mesmos, ordenando de forma decresce valor.

In [4]:
query = "SELECT NOME_ORGAO, SUM(VALOR_DESPESA) AS VALOR_TOTAL\
         FROM DESPESA_PUBLICA NATURAL JOIN ORGAO\
         WHERE ANO_DESPESA = 2018\
         GROUP BY NOME_ORGAO\
         ORDER BY VALOR_TOTAL DESC;"

df = pd.read_sql_query(query, conn);
df

                                       NOME_ORGAO  VALOR_TOTAL
0                            Ministério da Defesa    353376.70
1            Ministério do Desenvolvimento Social    278586.35
2   Ministério da Agricultura, Pecuária e Abastec     90836.51
3                          Ministério da Educação     64007.82
4                             Ministério da Saúde     50971.19
5   Ministério da Ciência, Tecnologia, Inovações          0.00
6                           Ministério da Fazenda         0.00
7               Ministério da Integração Nacional         0.00
8       Ministério da Justiça e Segurança Pública         0.00
9              Ministério das Relações Exteriores         0.00
10                    Ministério do Meio Ambiente         0.00
11                Ministério dos Direitos Humanos         0.00
12  Ministério dos Transportes, Portos e Aviação          0.00
13                       Presidência da República         0.00

## Questão 4
Liste o mês e ano, modalidade, programa de governo e valor de todas as despesas do órgao Ministério da Fazenda no primeiro semestre de 2018

In [5]:
query = "SELECT MES_DESPESA, ANO_DESPESA, MODALIDADE_DESPESA, NOME_PROGRAMA_GOVERNO, VALOR_DESPESA\
         FROM DESPESA_PUBLICA NATURAL JOIN ORGAO NATURAL JOIN PROGRAMA_GOVERNO\
         WHERE NOME_ORGAO = 'Ministério da Fazenda' AND ANO_DESPESA = 2018 AND MES_DESPESA <= 6;"

df = pd.read_sql_query(query, conn);
df

,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,NOME_PROGRAMA_GOVERNO,VALOR_DESPESA
0,4,2018,Reserva de Contingência,GESTAO AEROPORTUARIA,0
1,1,2018,Reserva de Contingência,BRASIL SEM MISERIA,0
2,2,2018,Reserva de Contingência,BRASIL SEM MISERIA,0
3,3,2018,Reserva de Contingência,BRASIL SEM MISERIA,0
4,4,2018,Reserva de Contingência,BRASIL SEM MISERIA,0
5,5,2018,Reserva de Contingência,BRASIL SEM MISERIA,0
6,6,2018,Reserva de Contingência,BRASIL SEM MISERIA,0

## Questão 7
Liste os órgãos governamentais e a quantidade de programas de governo distintos envolvidos nas despesas públicas desses órgãos. Nesta consulta, desconsidere valores de despesa negativos ou iguais a zero no período.

In [6]:
query = "SELECT NOME_ORGAO, COUNT(*)\
         FROM (\
             SELECT DISTINCT NOME_ORGAO, COD_PROGRAMA_GOVERNO\
             FROM DESPESA_PUBLICA NATURAL JOIN ORGAO NATURAL JOIN PROGRAMA_GOVERNO\
             WHERE VALOR_DESPESA > 0\
         )\
         GROUP BY NOME_ORGAO"

df = pd.read_sql_query(query, conn);
df

                                      NOME_ORGAO  COUNT(*)
0  Ministério da Agricultura, Pecuária e Abastec         2
1                           Ministério da Defesa         2
2                         Ministério da Educação         4
3                            Ministério da Saúde         2
4           Ministério do Desenvolvimento Social         1

## Questão 8
Liste os nomes das subfunções das despesas públicas envolvidas para cada programa de governo. Sua consulta deve retornar o nome do programa de governo, a subfunção da despesa, a quantidade de entradas de despesas públicas e o valor total dessas despesas.

In [7]:
query = "SELECT NOME_PROGRAMA_GOVERNO, NOME_SUBFUNCAO, COUNT(*), SUM(VALOR_DESPESA)\
         FROM DESPESA_PUBLICA NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN SUBFUNCAO NATURAL JOIN PROGRAMA_GOVERNO\
         GROUP BY NOME_PROGRAMA_GOVERNO, NOME_SUBFUNCAO"

df = pd.read_sql_query(query, conn);
df

,NOME_PROGRAMA_GOVERNO,NOME_SUBFUNCAO,COUNT(*),SUM(VALOR_DESPESA)
0,BRASIL SEM MISERIA,Alimentação e nutrição,112,100373.55
1,BRASIL SEM MISERIA,Assistência comunitária,117,227883.77
2,BRASIL SEM MISERIA,Comunicação social,1,0.00
3,BRASIL SEM MISERIA,Difusão do conhecimento científico e tecnológico,13,0.00
4,BRASIL SEM MISERIA,Educação infantil,2,0.00
5,BRASIL SEM MISERIA,Extensão rural,17,0.00
6,BRASIL SEM MISERIA,Fomento ao trabalho,1,0.00
7,BRASIL SEM MISERIA,Outros encargos especiais,12,0.00
8,BRASIL SEM MISERIA,Preservação e conservação ambiental,1,0.00
9,BRASIL SEM MISERIA,Promoção comercial,18,0.00
10,BRASIL SEM MISERIA,Recursos hídricos,34,0.00
11,BRASIL SEM MISERIA,Saneamento básico rural,27,0.00
12,BRASIL SEM MISERIA,Tecnologia da informação,26,58918.28
13,CADEIAS PUBLICAS,Custódia e reintegração social,9,0.00
14,CIENCIA SEM FRONTEIRAS,Desenvolvimento científico,12,0.00
15,CIENCIA SEM FRONTEIRAS,Ensino superior,12,0.00
16,CONTROLE DO CANCER,Assistência hospitalar e ambulatorial,40,38971.19
17,"CRACK, E POSSIVEL VENCER",Administração geral,1,0.00
18,"CRACK, E POSSIVEL VENCER",Assistência comunitária,12,0.00
19,"CRACK, E POSSIVEL VENCER",Assistência hospitalar e ambulatorial,19,0.00
20,"CRACK, E POSSIVEL VENCER",Atenção básica,5,0.00
21,"CRACK, E POSSIVEL VENCER",Comunicação social,1,0.00
22,"CRACK, E POSSIVEL VENCER","Direitos individuais, coletivos e difusos",46,0.00
23,"CRACK, E POSSIVEL VENCER",Formação de recursos humanos,1,0.00
24,"CRACK, E POSSIVEL VENCER",Policiamento,7,0.00
25,CRIMINALIDADE VIOLENTA,Policiamento,1,0.00
26,DESASTRES NATURAIS,Defesa civil,6,0.00
27,DESASTRES NATURAIS,Desenvolvimento científico,4,0.00
28,ENAFRON,Policiamento,14,0.00
29,ENEM,Educação básica,53,334262.06
...,...,...,...,...
35,MAIS MEDICOS,Formação de recursos humanos,2,0.00
36,MELHOR EM CASA,Assistência hospitalar e ambulatorial,15,0.00
37,MELHOR EM CASA,Atenção básica,1,0.00
38,OLIMPIADAS,Defesa terrestre,8,0.00
39,OLIMPIADAS,Informação e inteligência,5,0.00
40,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,Atenção básica,2,0.00
41,PRONATEC,Ensino profissional,33,60262.46
42,PROVA BRASIL,Educação básica,22,0.00
43,REDE CEGONHA,Assistência hospitalar e ambulatorial,38,1210.00
44,REGULARIZACAO FUNDIARIA,Normatização e fiscalização,2,0.00
45,REGULARIZACAO FUNDIARIA,Ordenamento territorial,29,1497.26
46,REGULARIZACAO FUNDIARIA,Reforma agrária,11,0.00
47,SATELITE (TELEBRAS),Desenvolvimento tecnológico e engenharia,7,0.00
48,SEGURO RURAL PRIVADO,Promoção da produção agropecuária,10,0.00
49,SINESP,Policiamento,9,0.00
50,SOS EMERGENCIA,Assistência hospitalar e ambulatorial,3,0.00
51,TERRITORIOS DA CIDADANIA,Extensão rural,14,0.00
52,UBS,Atenção básica,9,0.00
53,"UPA (INVESTIMENTO, CUSTEIO E COMPLEXO DE REGUL...",Assistência hospitalar e ambulatorial,12,0.00
54,VIOLENCIA NO TRANSITO,Policiamento,15,0.00
55,VIVER SEM LIMITE,Assistência ao portador de deficiência,5,0.00
56,VIVER SEM LIMITE,Assistência comunitária,19,0.00
57,VIVER SEM LIMITE,Assistência hospitalar e ambulatorial,56,0.00
58,VIVER SEM LIMITE,Atenção básica,18,0.00
59,VIVER SEM LIMITE,Desenvolvimento científico,8,0.00
60,VIVER SEM LIMITE,Desenvolvimento tecnológico e engenharia,11,0.00
61,VIVER SEM LIMITE,Educação básica,1,0.00
62,VIVER SEM LIMITE,Ensino superior,19,0.00
63,VIVER SEM LIMITE,Normatização e fiscalização,11,0.00
64,VIVER SEM LIMITE,Transferências para a educação básica,2,0.00

## Questão 9
Liste todas as despesas públicas (código da despesa, mês e ano da despesa, modalidade, valor) em que órgão responsável é aquele que possui o maior número de órgãos subordinados.

In [8]:
query = "SELECT COD_ORGAO, COD_DESPESA, MES_DESPESA, ANO_DESPESA, MODALIDADE_DESPESA, VALOR_DESPESA\
         FROM DESPESA_PUBLICA NATURAL JOIN (\
             SELECT COD_ORGAO, MAX(QTD_ORGAOS_SUBORDINADOS)\
             FROM ORGAO\
         )"

df = pd.read_sql_query(query, conn);
df

,COD_ORGAO,COD_DESPESA,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,VALOR_DESPESA
0,26000,196,10,2018,Reserva de Contingência,0.0
1,26000,197,1,2018,Reserva de Contingência,0.0
2,26000,198,2,2018,Reserva de Contingência,0.0
3,26000,199,3,2018,Reserva de Contingência,0.0
4,26000,200,4,2018,Reserva de Contingência,0.0
5,26000,201,5,2018,Reserva de Contingência,0.0
6,26000,202,6,2018,Reserva de Contingência,0.0
7,26000,203,7,2018,Reserva de Contingência,0.0
8,26000,204,9,2018,Reserva de Contingência,0.0
9,26000,205,10,2018,Reserva de Contingência,0.0
10,26000,206,11,2018,Reserva de Contingência,0.0
11,26000,207,12,2018,Reserva de Contingência,0.0
12,26000,208,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
13,26000,209,6,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
14,26000,210,7,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
15,26000,211,8,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
16,26000,212,9,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
17,26000,213,11,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
18,26000,214,12,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,0.0
19,26000,215,1,2018,Reserva de Contingência,0.0
20,26000,216,2,2018,Reserva de Contingência,0.0
21,26000,217,3,2018,Reserva de Contingência,0.0
22,26000,218,4,2018,Reserva de Contingência,0.0
23,26000,219,5,2018,Reserva de Contingência,0.0
24,26000,220,6,2018,Reserva de Contingência,0.0
25,26000,221,7,2018,Reserva de Contingência,0.0
26,26000,222,8,2018,Reserva de Contingência,0.0
27,26000,223,9,2018,Reserva de Contingência,0.0
28,26000,224,10,2018,Reserva de Contingência,0.0
29,26000,225,11,2018,Reserva de Contingência,0.0
...,...,...,...,...,...,...
264,26000,460,3,2018,Reserva de Contingência,0.0
265,26000,461,4,2018,Reserva de Contingência,0.0
266,26000,462,5,2018,Reserva de Contingência,0.0
267,26000,463,6,2018,Reserva de Contingência,0.0
268,26000,464,7,2018,Reserva de Contingência,0.0
269,26000,465,8,2018,Reserva de Contingência,0.0
270,26000,466,9,2018,Reserva de Contingência,0.0
271,26000,467,10,2018,Reserva de Contingência,0.0
272,26000,468,11,2018,Reserva de Contingência,0.0
273,26000,469,12,2018,Reserva de Contingência,0.0
274,26000,470,1,2018,Reserva de Contingência,0.0
275,26000,471,2,2018,Reserva de Contingência,0.0
276,26000,472,3,2018,Reserva de Contingência,0.0
277,26000,473,4,2018,Reserva de Contingência,0.0
278,26000,474,5,2018,Reserva de Contingência,0.0
279,26000,475,6,2018,Reserva de Contingência,0.0
280,26000,476,8,2018,Reserva de Contingência,0.0
281,26000,477,12,2018,Reserva de Contingência,0.0
282,26000,478,1,2018,Reserva de Contingência,0.0
283,26000,479,2,2018,Reserva de Contingência,0.0
284,26000,480,3,2018,Reserva de Contingência,0.0
285,26000,481,4,2018,Reserva de Contingência,0.0
286,26000,482,5,2018,Reserva de Contingência,0.0
287,26000,483,6,2018,Reserva de Contingência,0.0
288,26000,484,7,2018,Reserva de Contingência,0.0
289,26000,485,8,2018,Reserva de Contingência,2400.0
290,26000,486,9,2018,Reserva de Contingência,0.0
291,26000,487,10,2018,Reserva de Contingência,0.0
292,26000,488,11,2018,Reserva de Contingência,0.0
293,26000,489,12,2018,Reserva de Contingência,0.0

# Questões Teóricas
## Conversão de Álgebra Relacional para SQL

## Questão 1
$\pi$ NOME_FUNCAO, NOME_SUBFUNCAO(FUNCAO $\bowtie$ DETALHAMENTO_FUNCAO $\bowtie$ SUBFUNCAO)

In [9]:
query = "SELECT DISTINCT NOME_FUNCAO, NOME_SUBFUNCAO\
        FROM FUNCAO NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN SUBFUNCAO"

df = pd.read_sql_query(query, conn);
df

              NOME_FUNCAO                                    NOME_SUBFUNCAO
0     Essencial à justiça                                Comunicação social
1         Defesa nacional                               Administração geral
2         Defesa nacional                                  Defesa terrestre
3       Segurança pública                               Administração geral
4       Segurança pública                                      Policiamento
5       Segurança pública                                      Defesa civil
6       Segurança pública                         Informação e inteligência
7      Assistência social                       Normatização e fiscalização
8      Assistência social                          Tecnologia da informação
9      Assistência social                                Comunicação social
10     Assistência social                           Assistência comunitária
11     Assistência social                            Alimentação e nutrição
12     Assistência social                                 Educação infantil
13     Assistência social                           Saneamento básico rural
14                  Saúde                      Formação de recursos humanos
15                  Saúde                                    Atenção básica
16                  Saúde             Assistência hospitalar e ambulatorial
17               Trabalho                               Fomento ao trabalho
18               Educação             Assistência hospitalar e ambulatorial
19               Educação                               Ensino profissional
20               Educação                                   Ensino superior
21               Educação                                   Educação básica
22               Educação             Transferências para a educação básica
23  Direitos da cidadania            Assistência ao portador de deficiência
24  Direitos da cidadania                    Custódia e reintegração social
25  Direitos da cidadania         Direitos individuais, coletivos e difusos
26              Urbanismo                           Assistência comunitária
27       Gestão ambiental               Preservação e conservação ambiental
28       Gestão ambiental                                 Recursos hídricos
29   Ciência e Tecnologia                        Desenvolvimento científico
30   Ciência e Tecnologia          Desenvolvimento tecnológico e engenharia
31            Agricultura  Difusão do conhecimento científico e tecnológico
32            Agricultura                 Promoção da produção agropecuária
33    Organização agrária                       Normatização e fiscalização
34    Organização agrária                           Ordenamento territorial
35    Organização agrária                                    Extensão rural
36    Organização agrária                                   Reforma agrária
37              Indústria                                Promoção comercial
38             Transporte                               Administração geral
39     Encargos especiais                         Outros encargos especiais

## Questão 2
$\pi$ MODALIDADE_DESPESA, VALOR_DESPESA, NOME_PROGRAMA_GOVERNO(PROGRAMA_GOVERNO
$\bowtie$ $\sigma$ MODALIDADE_DESPESA='Reserva de Contingência'(DESPESA_PUBLICA))

In [10]:
query = "SELECT DISTINCT MODALIDADE_DESPESA, VALOR_DESPESA, NOME_PROGRAMA_GOVERNO\
        FROM PROGRAMA_GOVERNO NATURAL JOIN DESPESA_PUBLICA\
        WHERE MODALIDADE_DESPESA = 'Reserva de Contingência'"

df = pd.read_sql_query(query, conn);
df

,MODALIDADE_DESPESA,VALOR_DESPESA,NOME_PROGRAMA_GOVERNO
0,Reserva de Contingência,0.00,BRASIL SEM MISERIA
1,Reserva de Contingência,0.00,VIOLENCIA NO TRANSITO
2,Reserva de Contingência,0.00,TERRITORIOS DA CIDADANIA
3,Reserva de Contingência,8215.70,BRASIL SEM MISERIA
4,Reserva de Contingência,3.42,BRASIL SEM MISERIA
5,Reserva de Contingência,81120.13,BRASIL SEM MISERIA
6,Reserva de Contingência,0.00,REGULARIZACAO FUNDIARIA
7,Reserva de Contingência,1497.26,REGULARIZACAO FUNDIARIA
8,Reserva de Contingência,0.00,SEGURO RURAL PRIVADO
9,Reserva de Contingência,0.00,VIVER SEM LIMITE
10,Reserva de Contingência,0.00,CIENCIA SEM FRONTEIRAS
11,Reserva de Contingência,0.00,GESTAO AEROPORTUARIA
12,Reserva de Contingência,0.00,DESASTRES NATURAIS
13,Reserva de Contingência,0.00,SATELITE (TELEBRAS)
14,Reserva de Contingência,0.00,MELHOR EM CASA
15,Reserva de Contingência,1210.00,REDE CEGONHA
16,Reserva de Contingência,0.00,REDE CEGONHA
17,Reserva de Contingência,0.00,CONTROLE DO CANCER
18,Reserva de Contingência,0.00,ENEM
19,Reserva de Contingência,135.36,ENEM
20,Reserva de Contingência,0.00,PROVA BRASIL
21,Reserva de Contingência,2000.00,PRONATEC
22,Reserva de Contingência,0.00,PRONATEC
23,Reserva de Contingência,18178.00,PRONATEC
24,Reserva de Contingência,28073.08,PRONATEC
25,Reserva de Contingência,385.38,PRONATEC
26,Reserva de Contingência,5900.00,PRONATEC
27,Reserva de Contingência,0.00,CADEIAS PUBLICAS
28,Reserva de Contingência,0.00,"CRACK, E POSSIVEL VENCER"
29,Reserva de Contingência,0.00,MAIS MEDICOS
30,Reserva de Contingência,2400.00,MAIS MEDICOS
31,Reserva de Contingência,0.00,CRIMINALIDADE VIOLENTA
32,Reserva de Contingência,0.00,OLIMPIADAS
33,Reserva de Contingência,0.00,SINESP
34,Reserva de Contingência,0.00,ENAFRON
35,Reserva de Contingência,0.00,"UPA (INVESTIMENTO, CUSTEIO E COMPLEXO DE REGUL..."
36,Reserva de Contingência,38971.19,CONTROLE DO CANCER
37,Reserva de Contingência,11000.00,MAIS MEDICOS
38,Reserva de Contingência,1000.00,MAIS MEDICOS
39,Reserva de Contingência,334126.70,ENEM
40,Reserva de Contingência,19250.00,BRASIL SEM MISERIA
41,Reserva de Contingência,58918.28,BRASIL SEM MISERIA

## Questão 3
$\pi$ VALOR_DESPESA, NOME_ORGAO(DESPESA_PUBLICA $\bowtie$ $\sigma$ NOME_ORGAO='Ministério da Fazenda'(ORGAO))

In [11]:
query = "SELECT DISTINCT VALOR_DESPESA, NOME_ORGAO\
        FROM DESPESA_PUBLICA NATURAL JOIN ORGAO\
        WHERE NOME_ORGAO = 'Ministério da Fazenda'"

df = pd.read_sql_query(query, conn);
df

   VALOR_DESPESA             NOME_ORGAO
0              0  Ministério da Fazenda

## Questão 4
$\pi$ NOME_PROGRAMA_GOVERNO, VALOR_DESPESA(DESPESA_PUBLICA $\bowtie$ $\sigma$ NOME_ORGAO='Ministério da Saúde'(ORGAO) $\bowtie$ PROGRAMA_GOVERNO)

In [12]:
query = "SELECT DISTINCT NOME_PROGRAMA_GOVERNO, VALOR_DESPESA\
        FROM DESPESA_PUBLICA NATURAL JOIN ORGAO NATURAL JOIN PROGRAMA_GOVERNO\
        WHERE NOME_ORGAO = 'Ministério da Saúde'"

df = pd.read_sql_query(query, conn);
df

                                NOME_PROGRAMA_GOVERNO  VALOR_DESPESA
0                                    VIVER SEM LIMITE           0.00
1                                      SOS EMERGENCIA           0.00
2                                      MELHOR EM CASA           0.00
3                                                 UBS           0.00
4   UPA (INVESTIMENTO, CUSTEIO E COMPLEXO DE REGUL...           0.00
5                                        REDE CEGONHA           0.00
6                                  CONTROLE DO CANCER           0.00
7                                  CONTROLE DO CANCER       38971.19
8                            CRACK, E POSSIVEL VENCER           0.00
9                                  BRASIL SEM MISERIA           0.00
10  PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...           0.00
11                                       MAIS MEDICOS           0.00
12                                       MAIS MEDICOS       11000.00
13                                       MAIS MEDICOS        1000.00